# Generated by Django 3.0.5 on 2020-06-04 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sde', '0003_auto_20200529_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入角色名', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EveCorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入军团名称', max_length=20)),
                ('ceo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='InvStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('belongto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='corp.EveCorporation')),
                ('invtype', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sde.Invtypes')),
            ],
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCorporation'),
        ),
    ]
