# Generated by Django 3.0.5 on 2020-07-06 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sde', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveAlliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入联盟名称', max_length=20, unique=True)),
                ('codename', models.CharField(help_text='联盟代号', max_length=20, unique=True)),
                ('ingame_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EveCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入游戏内的角色名，必须与游戏内的角色名称完全一致', max_length=20, unique=True)),
                ('ingame_id', models.IntegerField(default=1)),
                ('bounduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('user_can_create_characters', '用户创建角色的权限'),),
            },
        ),
        migrations.CreateModel(
            name='EveCorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入军团名称', max_length=20, unique=True)),
                ('codename', models.CharField(help_text='军团代号', max_length=20, unique=True)),
                ('ingame_id', models.IntegerField(default=1)),
                ('dftdiscount', models.IntegerField(default=100)),
                ('refuseVerification', models.BooleanField(default=False)),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveAlliance')),
                ('ceo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCharacter')),
            ],
            options={
                'permissions': (('corp_hr', '军团人事相关的权限'), ('corp_info_edit', '更新军团设置的权限')),
            },
        ),
        migrations.CreateModel(
            name='sellState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(auto_now_add=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp.EveCorporation')),
                ('invtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Invtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('dkp', models.IntegerField(default=0)),
                ('donate', models.IntegerField(default=0)),
                ('pcharacter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCharacter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('user_can_set_pcharacter', '用户设定主角色的权限'),),
            },
        ),
        migrations.CreateModel(
            name='InvStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('sell', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('sellclrdate', models.DateTimeField(blank=True, null=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp.EveCorporation')),
                ('invtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Invtypes')),
            ],
            options={
                'permissions': (('can_update_invstorage', '更新库存数据的权限'),),
            },
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCorporation'),
        ),
        migrations.CreateModel(
            name='corpMiniBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=500)),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp.EveCorporation')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted'],
                'permissions': (('corp_blogger', '编辑军团公告的权限'),),
            },
        ),
    ]
