# Generated by Django 3.0.5 on 2020-06-09 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20200529_1716'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='bounduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
