# Generated by Django 3.0.5 on 2020-06-10 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20200529_1716'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corp', '0002_auto_20200610_0047'),
    ]

    operations = [

        migrations.AddField(
            model_name='evecharacter',
            name='ingame_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evecorporation',
            name='ingame_id',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcharacter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCharacter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
