# Generated by Django 3.0.5 on 2020-06-10 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20200529_1716'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corp', '0003_auto_20200610_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
