# Generated by Django 3.0.5 on 2020-06-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20200529_1716'),
        ('corp', '0005_auto_20200610_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invstorage',
            name='belongto',
        ),
        migrations.AddField(
            model_name='invstorage',
            name='corp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='corp.EveCorporation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invstorage',
            name='updatetime',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='name',
            field=models.CharField(help_text='输入角色名', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='evecorporation',
            name='name',
            field=models.CharField(help_text='输入军团名称', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invstorage',
            name='invtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sde.Invtypes'),
        ),
    ]
