# Generated by Django 3.0.5 on 2020-06-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0006_auto_20200614_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evecharacter',
            options={'permissions': (('user_can_create_characters', '用户创建角色的权限'),)},
        ),
        migrations.AlterModelOptions(
            name='invstorage',
            options={'permissions': (('can_update_invstorage', '更新库存数据的权限'),)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('user_can_set_pcharacter', '用户设定主角色的权限'),)},
        ),
    ]
