# Generated by Django 3.0.5 on 2020-06-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0008_evecorporation_dftdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evecorporation',
            options={'permissions': (('corp_hr', '军团人事相关的权限'),)},
        ),
    ]
