# Generated by Django 3.0.5 on 2020-06-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_auto_20200624_1759'),
        ('corp', '0009_auto_20200626_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='invstorage',
            name='sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invstorage',
            name='sellclrdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='sellState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.IntegerField(default=0)),
                ('updatetime', models.DateField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corp.EveCorporation')),
                ('invtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sde.Invtypes')),
            ],
        ),
    ]
