# Generated by Django 3.0.5 on 2020-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0010_auto_20200627_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invstorage',
            name='sellclrdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invstorage',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
