# Generated by Django 3.0.5 on 2020-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0011_auto_20200627_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellstate',
            name='updatetime',
            field=models.DateTimeField(),
        ),
    ]
