# Generated by Django 3.0.5 on 2020-06-27 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0012_auto_20200627_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellstate',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellstate',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
