# Generated by Django 3.0.5 on 2020-06-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0013_auto_20200627_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveAlliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入联盟名称', max_length=20, unique=True)),
                ('codename', models.CharField(blank=True, help_text='联盟代号', max_length=20, null=True)),
                ('ingame_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='evecorporation',
            name='codename',
            field=models.CharField(blank=True, help_text='军团代号', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evecorporation',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveAlliance'),
        ),
    ]
