# Generated by Django 3.0.5 on 2020-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0014_auto_20200627_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evealliance',
            name='codename',
            field=models.CharField(help_text='联盟代号', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='evecorporation',
            name='codename',
            field=models.CharField(help_text='军团代号', max_length=20, unique=True),
        ),
    ]
