# Generated by Django 3.0.5 on 2020-06-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_auto_20200624_1759'),
        ('corp', '0016_auto_20200628_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invstorage',
            name='invtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sde.Invtypes'),
        ),
        migrations.AlterField(
            model_name='sellstate',
            name='invtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sde.Invtypes'),
        ),
    ]
