# Generated by Django 3.0.5 on 2020-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0018_auto_20200628_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invstorage',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
