# Generated by Django 3.0.5 on 2020-06-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0023_auto_20200628_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='corpMiniBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp.EveCorporation')),
            ],
            options={
                'ordering': ['posted'],
                'permissions': (('corp_blogger', '编辑军团公告的权限'),),
            },
        ),
    ]
