# Generated by Django 3.0.5 on 2020-06-30 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corp', '0024_corpminiblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpminiblog',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpminiblog',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='bounduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveCorporation'),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='name',
            field=models.CharField(help_text='输入游戏内的角色名，必须与游戏内的角色名称完全一致', max_length=20, unique=True),
        ),
    ]
