# Generated by Django 3.0.5 on 2020-07-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0025_auto_20200630_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpminiblog',
            options={'ordering': ['-posted'], 'permissions': (('corp_blogger', '编辑军团公告的权限'),)},
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
