# Generated by Django 3.0.5 on 2020-07-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0027_auto_20200703_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evecorporation',
            options={'permissions': (('corp_hr', '军团人事相关的权限'), ('corp_info_edit', '更新军团设置的权限'))},
        ),
    ]
