# Generated by Django 3.0.5 on 2020-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0028_auto_20200703_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dkp',
            field=models.IntegerField(default=0),
        ),
    ]
