# Generated by Django 3.0.5 on 2020-07-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0029_profile_dkp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='donate',
            field=models.IntegerField(default=0),
        ),
    ]
