# Generated by Django 3.0.5 on 2020-07-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0030_profile_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecorporation',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corp.EveAlliance'),
        ),
    ]
