# Generated by Django 3.0.5 on 2020-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0031_auto_20200705_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecorporation',
            name='refuseVerification',
            field=models.BooleanField(default=False),
        ),
    ]
