# Generated by Django 3.0.5 on 2020-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=100)),
                ('subTitle', models.CharField(max_length=100)),
                ('footInfo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('inviteRegOnly', models.BooleanField(default=False)),
                ('underMaintaining', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='generalMiniBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expire', models.DateTimeField()),
            ],
        ),
    ]
