# Generated by Django 3.0.5 on 2020-07-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donater', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('r', 'RMB'), ('i', 'ISK'), ('o', '其他')], default='r', help_text='捐助类型', max_length=1)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('donateDate', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='generalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=100)),
                ('subTitle', models.CharField(max_length=100)),
                ('headInfo', models.TextField(blank=True, max_length=500, null=True)),
                ('footInfo', models.TextField(max_length=1000)),
                ('version', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, max_length=5000, null=True)),
                ('inviteRegOnly', models.BooleanField(default=False)),
                ('underMaintaining', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='generalMiniBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expire', models.DateTimeField()),
            ],
        ),
    ]
