# Generated by Django 3.0.5 on 2020-07-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200630_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='headInfo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
