# Generated by Django 3.0.5 on 2020-07-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generalinfo_headinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='headInfo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
