# Generated by Django 3.0.5 on 2020-07-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200705_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='footInfo',
            field=models.TextField(max_length=500),
        ),
    ]
