# Generated by Django 3.0.5 on 2020-07-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200705_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='donateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donater', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('r', 'RMB'), ('i', 'ISK'), ('o', '其他')], default='r', help_text='捐助类型', max_length=1)),
                ('info', models.CharField(max_length=200)),
                ('donateDate', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
