# Generated by Django 3.0.5 on 2020-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200705_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='about',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='footInfo',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='headInfo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
