# Generated by Django 3.0.5 on 2020-07-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200705_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donateinfo',
            options={'ordering': ['-amount']},
        ),
    ]
