# Generated by Django 3.0.5 on 2020-05-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eveicons',
            fields=[
                ('iconid', models.AutoField(db_column='iconID', primary_key=True, serialize=False)),
                ('iconfile', models.TextField(blank=True, db_column='iconFile', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('obsolete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eveIcons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invtypes',
            fields=[
                ('typeid', models.AutoField(db_column='typeID', primary_key=True, serialize=False)),
                ('groupid', models.IntegerField(blank=True, db_column='groupID', null=True)),
                ('typename', models.TextField(blank=True, db_column='typeName', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mass', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('packagedvolume', models.TextField(blank=True, db_column='packagedVolume', null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
                ('portionsize', models.IntegerField(blank=True, db_column='portionSize', null=True)),
                ('factionid', models.IntegerField(blank=True, db_column='factionID', null=True)),
                ('raceid', models.TextField(blank=True, db_column='raceID', null=True)),
                ('baseprice', models.TextField(blank=True, db_column='basePrice', null=True)),
                ('published', models.IntegerField(blank=True, null=True)),
                ('marketgroupid', models.IntegerField(blank=True, db_column='marketGroupID', null=True)),
                ('graphicid', models.IntegerField(blank=True, db_column='graphicID', null=True)),
                ('radius', models.TextField(blank=True, null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('soundid', models.IntegerField(blank=True, db_column='soundID', null=True)),
                ('soffactionname', models.TextField(blank=True, db_column='sofFactionName', null=True)),
                ('sofmaterialsetid', models.IntegerField(blank=True, db_column='sofMaterialSetID', null=True)),
                ('metagroupid', models.IntegerField(blank=True, db_column='metaGroupID', null=True)),
                ('variationparenttypeid', models.IntegerField(blank=True, db_column='variationparentTypeID', null=True)),
            ],
            options={
                'db_table': 'invTypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marketgroups',
            fields=[
                ('marketgroupid', models.AutoField(db_column='marketGroupID', primary_key=True, serialize=False)),
                ('descriptionid', models.TextField(blank=True, db_column='descriptionID', null=True)),
                ('hastypes', models.IntegerField(blank=True, db_column='hasTypes', null=True)),
                ('iconid', models.IntegerField(blank=True, db_column='iconID', null=True)),
                ('nameid', models.TextField(blank=True, db_column='nameID', null=True)),
                ('parentgroupid', models.ForeignKey(blank=True, db_column='parentGroupID', null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Marketgroups')),
            ],
            options={
                'db_table': 'marketGroups',
                'managed': True,
            },
        ),
    ]
