# Generated by Django 3.0.5 on 2020-05-28 13:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketgroups',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketgroups',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketgroups',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketgroups',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invtypes',
            name='marketgroupid',
            field=models.IntegerField(blank=True, db_column='marketgroupID', null=True),
        ),
        migrations.AlterField(
            model_name='marketgroups',
            name='parentgroupid',
            field=mptt.fields.TreeForeignKey(blank=True, db_column='parentGroupID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sde.Marketgroups'),
        ),
    ]
