# Generated by Django 3.0.5 on 2020-06-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20200529_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketgroups',
            options={'managed': True, 'permissions': (('user_can_use_market', '用户访问市场数据的权限'),)},
        ),
    ]
