# Generated by Django 3.0.5 on 2020-06-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': (('user_can_use_cart', '用户使用购物车的权限'),)},
        ),
    ]
