# Generated by Django 3.0.5 on 2020-06-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sde', '0003_auto_20200529_1716'),
        ('corp', '0006_auto_20200614_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='订单UID', primary_key=True, serialize=False)),
                ('itemcount', models.IntegerField(default=0)),
                ('totalprice', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('o', '已提交'), ('f', '已完成'), ('e', '异常')], default='m', help_text='订单状态', max_length=1)),
                ('createdate', models.DateTimeField(auto_now_add=True, help_text='订单的创建日期')),
                ('finishdate', models.DateTimeField(blank=True, help_text='订单的完成日期', null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp.EveCharacter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdate'],
            },
        ),
        migrations.CreateModel(
            name='regularOrderUnit',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='单元UID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, help_text='物品数量')),
                ('price', models.IntegerField(default=0, help_text='单价')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Invtypes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
