# Generated by Django 3.0.5 on 2020-06-14 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='itemcount',
        ),
        migrations.AlterField(
            model_name='order',
            name='createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 1, 47, 23, 367069), help_text='订单的创建日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('o', '已提交'), ('f', '已完成'), ('e', '异常')], default='o', help_text='订单状态', max_length=1),
        ),
    ]
