# Generated by Django 3.0.5 on 2020-06-14 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200615_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 14, 18, 10, 53, 711345, tzinfo=utc), help_text='订单的创建日期'),
        ),
    ]
