# Generated by Django 3.0.5 on 2020-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200615_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('o', '已提交'), ('f', '已完成'), ('c', '已取消'), ('e', '异常')], default='o', help_text='订单状态', max_length=1),
        ),
    ]
