# Generated by Django 3.0.5 on 2020-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200616_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemcount',
            field=models.IntegerField(default=0),
        ),
    ]
