# Generated by Django 3.0.5 on 2020-06-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0006_auto_20200614_2026'),
        ('order', '0006_order_itemcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='corp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corp.EveCorporation'),
            preserve_default=False,
        ),
    ]
