# Generated by Django 3.0.5 on 2020-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_corp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='regularorderunit',
            name='status',
            field=models.CharField(blank=True, choices=[('w', '等待处理'), ('s', '已发放'), ('p', '部分发放'), ('e', '无货')], default='w', help_text='物品状态', max_length=1),
        ),
    ]
