# Generated by Django 3.0.5 on 2020-06-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200619_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-createdate'], 'permissions': (('can_process_orders', '查看成员订单、对其进行处理的权限'),)},
        ),
    ]
