# Generated by Django 3.0.5 on 2020-06-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200624_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-createdate'], 'permissions': (('can_process_orders', '查看成员订单、对其进行处理的权限'), ('user_can_create_orders', '用户创建\\取消订单的权限'))},
        ),
    ]
