# Generated by Django 3.0.5 on 2020-06-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_auto_20200624_1759'),
        ('order', '0011_auto_20200624_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularorderunit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sde.Invtypes'),
        ),
    ]
