# Generated by Django 3.0.5 on 2020-06-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_auto_20200624_1759'),
        ('order', '0014_auto_20200628_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularorderunit',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sde.Invtypes'),
            preserve_default=False,
        ),
    ]
