# Generated by Django 3.0.5 on 2020-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200628_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('o', '已提交'), ('f', '已完成'), ('c', '已取消'), ('p', '已完成-部分未发放')], default='o', help_text='订单状态', max_length=1),
        ),
    ]
